spring:
  datasource:
    url: jdbc:mysql://payment-mysql:3306/paymentDb?allowPublicKeyRetrieval=true&useSSL=false
    username: pathum
    password: P@thum25
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}