
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservationDb?allowPublicKeyRetrieval=true&useSSL=false
    username: pathum
    password: P@thum25
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
