server:
  port: 9090
spring:
  application:
    name: api-gw
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: {http://localhost:8761/eureka/:http://discovery-service:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/check_token
      jwt:
        key-value: 123456

    client:
      client-id: mobile
      client-secret: pin
